version: '3'
      
services:
  deep:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_APP=deepfaq.py
    command: python -m flask run --port 3000 --host 0.0.0.0
    ports:
      - "3030:3000"
